# Generated by Django 4.2.3 on 2023-08-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0002_alter_advertisement_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'managed': True, 'verbose_name': 'advertisements', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table='',
        ),
    ]
