# Generated by Django 4.2.3 on 2023-08-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0003_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'managed': True, 'verbose_name': 'advertisements', 'verbose_name_plural': 'advertisements'},
        ),
    ]
