# Generated by Django 4.2.3 on 2023-08-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0006_alter_advertisement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='auction',
            field=models.BooleanField(default=False, verbose_name='торг'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='prise',
            field=models.FloatField(default=0, verbose_name='цена'),
            preserve_default=False,
        ),
    ]
