# Generated by Django 4.2.3 on 2023-08-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0007_advertisement_auction_advertisement_prise'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновление'),
        ),
    ]
