# Generated by Django 4.2.3 on 2023-08-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lesson_4', '0009_alter_advertisement_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='coortun',
            field=models.ImageField(default='', upload_to='media', verbose_name='изображения'),
            preserve_default=False,
        ),
    ]
